package db

import (
	"database/sql"
	"fmt"
)

func init() {
	RegisterMigration(Migration{
		Version: 14,
		Name:    "feature_stages_bolt_number",
		Up:      migration014FeatureStagesBoltNumber,
	})
}

// migration014FeatureStagesBoltNumber makes construction stages 3.1-3.5
// per-Bolt (AIDLC v2 spec: each Bolt is a full pass through 3.1-3.5).
// Non-construction stages keep a single row at bolt_number=0.
//
// Steps:
//  1. Add bolt_number column (default 0).
//  2. Drop the old UNIQUE(feature_id, stage_id) constraint.
//  3. Add UNIQUE(feature_id, stage_id, bolt_number).
//
// Existing rows backfill to bolt_number=0 (non-construction semantics).
// Construction Bolt rows are created on demand by InitBoltStages.
func migration014FeatureStagesBoltNumber(tx *sql.Tx) error {
	// 1. Add the column if missing.
	var colExists int
	row := tx.QueryRow(`SELECT COUNT(*) FROM information_schema.columns WHERE table_name = $1 AND column_name = $2`, "feature_stages", "bolt_number")
	if err := row.Scan(&colExists); err != nil {
		return fmt.Errorf("checking bolt_number column: %w", err)
	}
	if colExists == 0 {
		if _, err := tx.Exec(`ALTER TABLE feature_stages ADD COLUMN bolt_number INTEGER NOT NULL DEFAULT 0`); err != nil {
			return fmt.Errorf("adding bolt_number column: %w", err)
		}
	}

	// 2. Drop the old unique constraint. Name is auto-generated by PG;
	//    find it dynamically rather than assuming a fixed name.
	var constraintName string
	err := tx.QueryRow(`
		SELECT conname FROM pg_constraint
		WHERE conrelid = 'feature_stages'::regclass
		  AND contype = 'u'
		  AND array_to_string(conkey, ',') = (
		    SELECT array_to_string(array_agg(attnum ORDER BY attnum), ',')
		    FROM pg_attribute
		    WHERE attrelid = 'feature_stages'::regclass
		      AND attname IN ('feature_id', 'stage_id')
		  )`).Scan(&constraintName)
	if err == nil && constraintName != "" {
		if _, err := tx.Exec(fmt.Sprintf(`ALTER TABLE feature_stages DROP CONSTRAINT IF EXISTS %s`, constraintName)); err != nil {
			return fmt.Errorf("dropping old unique constraint %s: %w", constraintName, err)
		}
	} else if err != sql.ErrNoRows {
		// Log but don't fail — the constraint may already be gone.
		_ = err
	}

	// 3. Add the new composite unique constraint.
	if _, err := tx.Exec(`CREATE UNIQUE INDEX IF NOT EXISTS idx_feature_stages_unique ON feature_stages(feature_id, stage_id, bolt_number)`); err != nil {
		return fmt.Errorf("creating composite unique index: %w", err)
	}

	return nil
}
